import { 
  MessageSquare, 
  Image as ImageIcon, 
  Languages, 
  BrainCircuit, 
  Download, 
  Youtube, 
  Music, 
  Instagram, 
  Scale, 
  Coins, 
  Code2, 
  Binary, 
  Key, 
  QrCode, 
  Info, 
  Type, 
  Hash, 
  FileText, 
  Palette, 
  Timer, 
  Weight, 
  Terminal, 
  Mic, 
  Cpu, 
  Globe, 
  GitCompare, 
  Database, 
  ShieldCheck, 
  UserCircle, 
  PencilLine,
  Volume2,
  FileSearch,
  CheckCircle2,
  Lock,
  Layout,
  Layers,
  Search,
  Monitor,
  Wifi,
  Zap,
  Calculator,
  Compass,
  CreditCard,
  Cloud,
  Eye,
  MousePointer2,
  CloudDownload,
  Share2,
  Smartphone,
  Video
} from 'lucide-react';
import { Tool } from './types';

export const TOOLS: Tool[] = [
  { id: 'ai-chat', name: 'Neural Engine', description: 'Advanced logic and technical synthesis system', icon: MessageSquare, category: 'AI', path: '/ai-chat' },
  { id: 'ai-image', name: 'VRAM Synthesis', description: 'High-fidelity visual asset generation framework', icon: ImageIcon, category: 'AI', path: '/ai-image' },
  { id: 'lang-learn', name: 'Linguistic Node', description: 'Multilingual data translation and learning protocol', icon: Languages, category: 'Education', path: '/lang-learn' },
  { id: 'quiz', name: 'Logic Assessment', description: 'Dynamic technical evaluation and testing unit', icon: BrainCircuit, category: 'Education', path: '/quiz' },
  { id: 'tiktok-dl', name: 'TikTok Downloader', description: 'Download TikTok media without watermarks', icon: Download, category: 'Media', path: '/tiktok-dl' },
  { id: 'youtube-dl', name: 'YouTube Pro', description: 'High-quality extraction for YouTube content', icon: Youtube, category: 'Media', path: '/youtube-dl' },
  { id: 'spotify-dl', name: 'Spotify Stream', description: 'Download tracks and playlists instantly', icon: Music, category: 'Media', path: '/spotify-dl' },
  { id: 'ig-dl', name: 'Instagram Guard', description: 'Resource extraction for IG stories and reels', icon: Instagram, category: 'Media', path: '/ig-dl' },
  { id: 'json-format', name: 'JSON Processor', description: 'Professional JSON formatting and validation', icon: Code2, category: 'Dev', path: '/json-format' },
  { id: 'base64', name: 'Base64 Codec', description: 'Encode and decode binary data streams', icon: Binary, category: 'Dev', path: '/base64' },
  { id: 'pass-gen', name: 'Entropy Generator', description: 'Cryptographically strong security credential generator', icon: Key, category: 'Utility', path: '/pass-gen' },
  { id: 'qr-gen', name: 'Matrix QR', description: 'Generate high-density custom response codes', icon: QrCode, category: 'Utility', path: '/qr-gen' },
  { id: 'ip-info', name: 'WA Intel', description: 'Deep OSINT metadata lookup for global phone numbers', icon: Info, category: 'Network', path: '/ip-info' },
  { id: 'ig-stalk', name: 'IG Intel', description: 'Deep Instagram profile analysis and search grounding', icon: Instagram, category: 'Network', path: '/ig-stalk' },
  { id: 'case-conv', name: 'Case Converter', description: 'Transform text casing professionally', icon: Type, category: 'Text', path: '/case-conv' },
  { id: 'word-count', name: 'Text Analytics', description: 'Deep analysis of text structure and timing', icon: Hash, category: 'Text', path: '/word-count' },
  { id: 'md-preview', name: 'Markdown Pro', description: 'Live professional Markdown environment', icon: FileText, category: 'Dev', path: '/md-preview' },
  { id: 'color-picker', name: 'Design Palette', description: 'Professional color selection for designers', icon: Palette, category: 'Utility', path: '/color-picker' },
  { id: 'timer', name: 'Precision Clock', description: 'Advanced countdown and stopwatch logic', icon: Timer, category: 'Utility', path: '/timer' },
  { id: 'bmi-calc', name: 'Health Metrics', description: 'Calculate precise body health indices', icon: Weight, category: 'Math', path: '/bmi-calc' },
  { id: 'ascii-gen', name: 'Visual ASCII', description: 'Transform typography into unique art', icon: Terminal, category: 'Text', path: '/ascii-gen' },
  { id: 'morse-conv', name: 'Signal Code', description: 'Advanced Morse communication processor', icon: Mic, category: 'Text', path: '/morse-conv' },
  { id: 'unit-conv', name: 'Metric System', description: 'Universal unit conversion framework', icon: Scale, category: 'Math', path: '/unit-conv' },
  { id: 'binary-conv', name: 'Data Bits', description: 'Binary to decimal conversion engine', icon: Cpu, category: 'Dev', path: '/binary-conv' },
  { id: 'url-codec', name: 'URL Encoder', description: 'Sanitize and encode web addresses', icon: Globe, category: 'Network', path: '/url-codec' },
  { id: 'diff-check', name: 'Code Compare', description: 'Identify data discrepancies instantly', icon: GitCompare, category: 'Dev', path: '/diff-check' },
  { id: 'sql-format', name: 'SQL Beautifier', description: 'Refine and structure query logic', icon: Database, category: 'Dev', path: '/sql-format' },
  { id: 'jwt-debug', name: 'Token Inspector', description: 'Secure JWT authentication debugging', icon: ShieldCheck, category: 'Dev', path: '/jwt-debug' },
  { id: 'ua-info', name: 'Client Details', description: 'Inspect browser and system signatures', icon: UserCircle, category: 'Network', path: '/ua-info' },
  { id: 'lorum-gen', name: 'Draft Content', description: 'High-fidelity typography content generation', icon: PencilLine, category: 'Text', path: '/lorum-gen' },
  { id: 'cur-conv', name: 'Exchange Rates', description: 'Real-time global currency data', icon: Coins, category: 'Math', path: '/cur-conv' },
  
  // 20 New Tools
  { id: 'text-speech', name: 'Speech Synthesis', description: 'Convert text to natural audio output', icon: Volume2, category: 'AI', path: '/text-speech' },
  { id: 'seo-tags', name: 'Meta Explorer', description: 'Generate professional SEO meta tags', icon: FileSearch, category: 'Dev', path: '/seo-tags' },
  { id: 'contrast', name: 'Accessibility', description: 'WCAG color contrast validation tool', icon: CheckCircle2, category: 'Utility', path: '/contrast' },
  { id: 'stutter-gen', name: 'Hash Security', description: 'Generate MD5, SHA256, and SHA512 hashes', icon: Lock, category: 'Utility', path: '/hash-gen' },
  { id: 'gradient-gen', name: 'Style Canvas', description: 'Beautiful CSS gradient generator', icon: Layout, category: 'Dev', path: '/gradient-gen' },
  { id: 'svg-optim', name: 'Vector Lab', description: 'Optimize SVG files for production use', icon: Layers, category: 'Dev', path: '/svg-optim' },
  { id: 'site-audit', name: 'Core Web Vitals', description: 'Analyze website performance metrics', icon: Search, category: 'Network', path: '/site-audit' },
  { id: 'screen-info', name: 'Display Matrix', description: 'Detailed monitor and display analysis', icon: Monitor, category: 'Network', path: '/screen-info' },
  { id: 'port-scan', name: 'Connectivity Scan', description: 'Network port and latency analysis', icon: Wifi, category: 'Network', path: '/port-scan' },
  { id: 'quick-math', name: 'Compute Core', description: 'High-precision scientific computational framework', icon: Calculator, category: 'Math', path: '/quick-math' },
  { id: 'timezone', name: 'Global Horizon', description: 'Compare world time zones accurately', icon: Compass, category: 'Utility', path: '/timezone' },
  { id: 'card-val', name: 'Security Verify', description: 'Luhn algorithm credit card validator', icon: CreditCard, category: 'Utility', path: '/card-val' },
  { id: 'weather', name: 'Atmo Data', description: 'Real-time precise weather forensics', icon: Cloud, category: 'Network', path: '/weather' },
  { id: 'vision-ai', name: 'Object Detection', description: 'AI visual recognition system', icon: Eye, category: 'AI', path: '/vision-ai' },
  { id: 'click-speed', name: 'Nerve Response', description: 'Test clicking precision and speed', icon: MousePointer2, category: 'Utility', path: '/click-speed' },
  { id: 'repo-stat', name: 'Cloud Repos', description: 'Analyze GitHub repository statistics', icon: CloudDownload, category: 'Dev', path: '/repo-stat' },
  { id: 'meta-share', name: 'Preview Hub', description: 'Visualize social media link previews', icon: Share2, category: 'Media', path: '/meta-share' },
  { id: 'device-info', name: 'Hardware Profiler', description: 'Complete device hardware audit', icon: Smartphone, category: 'Network', path: '/device-info' },
  { id: 'canvas-draw', name: 'Studio Board', description: 'Interactive collaborative canvas tool', icon: PencilLine, category: 'Media', path: '/canvas-draw' },
  { id: 'video-trim', name: 'Media Snipper', description: 'Basic client-side video processing', icon: Video, category: 'Media', path: '/video-trim' },
];

